const appetizers = [
    {
        name: "Paneer Tikka",
        description: "Grilled cubes of paneer marinated in a flavorful blend of spices and yogurt, cooked to perfection.",
        price: 200,
        image: { url: "https://myfoodstory.com/wp-content/uploads/2017/02/Oven-Baked-Tandoori-Paneer-Tikka-2-500x375.jpg" },
        category: "appetizers",
        type: "veg",
    },
    {
        name: "Hara Bhara Kebab",
        description: "Delicious spinach-based kebabs loaded with vegetables, aromatic spices, and shallow-fried for a crispy finish.",
        price: 180,
        image: { url: "https://www.vegrecipesofindia.com/wp-content/uploads/2013/01/hara-bhara-kabab-recipe-1.jpg" },
        category: "appetizers",
        type: "veg",
    },
    {
        name: "Aloo Tikki with Chole",
        description: "Crispy potato patties served alongside spicy chickpea curry, garnished with tangy chutneys and onions.",
        price: 150,
        image: { url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWVUoDLoO_cF0U-pOebGUn7PMk9KxF3adS7g&s" },
        category: "appetizers",
        type: "veg",
    },
    {
        name: "Vegetable Samosa",
        description: "Golden-brown, flaky pastry stuffed with a savory, spiced mixture of potatoes, peas, and fragrant spices.",
        price: 120,
        image: { url: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi1ZaIYcczCiiZ9Ea2gwuXWHgeByCYjE6ojW8innb2csVw5fLqj_IUbrGTOwwqfOQbwxhkL2SFsJ5LOLh713Vx7-SHM4UjQLYRIBJr2gtLZycfyAAcKFHCFz-iS7tOx7SeKfZ0nQrMjbCPAL1WYW3QAz911PJt2yOTAUYuR1W_n0y4LNs25XTyEmJlADxE/s4693/Cover%20samosas.jpg" },
        category: "appetizers",
        type: "veg",
    },
    {
        name: "Spring Rolls",
        description: "Crispy rolls packed with a delightful filling of seasoned vegetables or noodles, fried to golden perfection.",
        price: 180,
        image: { url: "https://www.sugarsaltmagic.com/wp-content/uploads/2023/01/Chinese-Spring-Rolls-4FEAT-500x500.jpg" },
        category: "appetizers",
        type: "veg",
    },
    {
        name: "Chicken Tikka",
        description: "Juicy chicken pieces marinated in rich spices and yogurt, then grilled for a smoky, charred flavor.",
        price: 250,
        image: { url: "https://spicecravings.com/wp-content/uploads/2020/01/Chicken-Tikka-2.jpg" },
        category: "appetizers",
        type: "nonVeg",
    },
    {
        name: "Chili Chicken",
        description: "Crispy fried chicken tossed in a spicy, tangy sauce with peppers, onions, and a hint of garlic.",
        price: 280,
        image: { url: "https://static.toiimg.com/thumb/53094926.cms?width=1200&height=900" },
        category: "appetizers",
        type: "nonVeg",
    },
    {
        name: "Garlic Chicken",
        description: "Tender chicken stir-fried with aromatic garlic, soy sauce, and herbs for a savory, umami-rich taste.",
        price: 260,
        image: { url: "https://www.eatwell101.com/wp-content/uploads/2021/10/Honey-Garlic-Chicken-Recipe.jpg" },
        category: "appetizers",
        type: "nonVeg",
    },
    {
        name: "Fish Tikka",
        description: "Chunks of marinated fish grilled to perfection, bursting with smoky flavor and a delicate texture.",
        price: 300,
        image: { url: "https://i.ytimg.com/vi/eFSauc959XE/maxresdefault.jpg" },
        category: "appetizers",
        type: "nonVeg",
    },
    {
        name: "Fish Amritsari",
        description: "Crispy fried fish coated in a spicy batter, inspired by traditional Amritsari flavors and cooking style.",
        price: 320,
        image: { url: "https://www.chefkunalkapur.com/wp-content/uploads/2021/03/amritsari-fried-fish-scaled-e1621348565229.jpeg?v=1618226070" },
        category: "appetizers",
        type: "nonVeg",
    },
    {
        name: "Mutton Shami Kebab",
        description: "Delicate mutton kebabs made with minced meat, lentils, and spices, cooked to a melt-in-your-mouth texture.",
        price: 350,
        image: { url: "https://www.chikplaza.com/wp-content/uploads/2017/11/Mutton-Shami.jpg" },
        category: "appetizers",
        type: "nonVeg",
    },
    {
        name: "D-Dine Special Tikka Platter",
        description: "A delightful mix of various tikkas, including chicken, paneer, and fish, perfect for group enjoyment.",
        price: 450,
        image: { url: "https://5.imimg.com/data5/FK/LS/GLADMIN-17925124/non-veg-platter-500x500.png" },
        category: "appetizers",
        type: "nonVeg",
    },
    {
        name: "D-Dine Special Prawns Koliwada",
        description: "Juicy prawns marinated in spices and deep-fried to golden crispiness, inspired by Koliwada-style cooking.",
        price: 400,
        image: { url: "https://vanitascorner.com/wp-content/uploads/2023/06/Prawns-koliwada-FB.jpg" },
        category: "appetizers",
        type: "nonVeg",
    },
    {
        name: "D-Dine Spicy Dahi Chaat",
        description: "A tangy yogurt-based chaat topped with spices, crunchy papdi, boiled potatoes, and sweet tamarind chutney.",
        price: 180,
        image: { url: "https://static.toiimg.com/thumb/52727664.cms?imgsize=126219&width=800&height=800" },
        category: "appetizers",
        type: "veg",
    },
];

module.exports = appetizers;
