const beverages = [
    {
        name: "Masala Chai",
        description: "A warm, spiced tea brewed with milk, ginger, cardamom, cloves, and aromatic Indian spices.",
        price: 100,
        image: { url: "https://zyanna.com/cdn/shop/files/zyanna-masala-chai-3.jpg?v=1718643762" },
        category: "beverages",
        type: "veg",
    },
    {
        name: "Fresh Lime Soda",
        description: "A revitalizing blend of lime juice, sparkling soda, and sugar, served chilled for ultimate refreshment.",
        price: 120,
        image: { url: "https://pariwaardelights.s3.us-east-1.amazonaws.com/uploads/all/sVrUbFMiciLGkhQvYxChD29vUKCxILUAAErx2RJG.jpg" },
        category: "beverages",
        type: "veg",
    },
    {
        name: "Mango Lassi",
        description: "A creamy yogurt-based drink blended with fresh, ripe mangoes and a hint of sweetness.",
        price: 150,
        image: { url: "https://www.cubesnjuliennes.com/wp-content/uploads/2019/05/Healthy-Mango-Lassi-Recipe.jpg" },
        category: "beverages",
        type: "veg",
    },
    {
        name: "Cold Coffee With Ice Cream",
        description: "A deliciously chilled coffee blended with milk, topped with a scoop of creamy vanilla ice cream.",
        price: 180,
        image: { url: "https://artofpalate.com/wp-content/uploads/2017/10/cold-coffee-recipes.jpg" },
        category: "beverages",
        type: "veg",
    },
    {
        name: "Iced Tea (Lemon or Peach)",
        description: "Chilled tea infused with the fruity sweetness of lemon or peach, served over ice for a refreshing twist.",
        price: 130,
        image: { url: "https://www.vegetarianventures.com/wp-content/uploads/2019/07/PeachLemonadeBlog-16-of-18.jpg" },
        category: "beverages",
        type: "veg",
    },
    {
        name: "Sweet Lassi",
        description: "A traditional Indian yogurt drink sweetened with sugar and flavored with aromatic cardamom or rose water.",
        price: 140,
        image: { url: "https://www.indianveggiedelight.com/wp-content/uploads/2023/01/sweet-lassi-recipe-featured.jpg" },
        category: "beverages",
        type: "veg",
    },
    {
        name: "Pineapple Juice",
        description: "Freshly extracted pineapple juice that is tangy, naturally sweet, and served chilled for a tropical vibe.",
        price: 100,
        image: { url: "https://cdn2.foodviva.com/static-content/food-images/pineapple-recipes/pineapple-juice-recipe/pineapple-juice-recipe.jpg" },
        category: "beverages",
        type: "veg",
    },
    {
        name: "Virgin Mojito",
        description: "A non-alcoholic mix of mint leaves, lime juice, sugar, and soda for a cool, refreshing drink.",
        price: 180,
        image: { url: "https://www.pastrywishes.com/wp-content/uploads/2022/06/virgin-mojito-with-sprite-square.jpg" },
        category: "beverages",
        type: "veg",
    },
    {
        name: "Buttermilk (Chaas)",
        description: "A savory yogurt-based drink seasoned with cumin, coriander, and ginger for a refreshing tangy flavor.",
        price: 90,
        image: { url: "https://www.cookwithmanali.com/wp-content/uploads/2017/06/Masala-Chaas-Recipe-500x500.jpg" },
        category: "beverages",
        type: "veg",
    },
    {
        name: "Chocolate Milkshake",
        description: "A rich, creamy milkshake made with premium chocolate, milk, and ice cream, topped with whipped cream.",
        price: 200,
        image: { url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiuHmGj6JWC8RxNcvny2MpaAXbB2pMUdKn-A&s" },
        category: "beverages",
        type: "veg",
    },
    {
        name: "D-Dine Special Carrot Juice",
        description: "Freshly juiced carrots blended with a hint of tangy lime and mint for a revitalizing experience.",
        price: 180,
        image: { url: "https://healthytasteoflife.com/wp-content/uploads/2021/09/carrot-juice-recipe-blender-or-juicer-simple.jpg" },
        category: "beverages",
        type: "veg",
    },
    {
        name: "D-Dine Special Rose & Hibiscus Cooler",
        description: "A floral and refreshing drink made with hibiscus petals, rose syrup, and served over ice.",
        price: 200,
        image: { url: "https://cdn.loveandlemons.com/wp-content/uploads/2023/05/hibiscus-tea-recipe.jpg" },
        category: "beverages",
        type: "veg",
    },
];

module.exports = beverages;
