const desserts = [
    {
        name: "Gulab Jamun",
        description: "Soft, golden dough balls soaked in aromatic sugar syrup flavored with cardamom and rose water for extra sweetness.",
        price: 120,
        image: { url: "https://chefadora.b-cdn.net/003f0f0351967a7cb6212a8d9bfaf889_f956154e73.jpg" },
        category: "desserts",
        type: "veg",
    },
    {
        name: "Rasgulla",
        description: "Light, spongy cheese balls soaked in a delicate sugar syrup, offering a sweet and chewy texture.",
        price: 150,
        image: { url: "https://www.palatesdesire.com/wp-content/uploads/2022/09/rasgulla-recipe@palates-desire.jpg" },
        category: "desserts",
        type: "veg",
    },
    {
        name: "Pista Kulfi",
        description: "Traditional Indian ice cream made with condensed milk, flavored with cardamom and saffron, and studded with pistachios.",
        price: 180,
        image: { url: "https://static.toiimg.com/thumb/84786580.cms?imgsize=157368&width=800&height=800" },
        category: "desserts",
        type: "veg",
    },
    {
        name: "Gajar Halwa",
        description: "A warm, comforting dessert made with grated carrots, milk, sugar, ghee, and garnished with nuts for extra flavor.",
        price: 140,
        image: { url: "https://i0.wp.com/kalimirchbysmita.com/wp-content/uploads/2016/01/Gajar-ka-Halwa-03.jpg" },
        category: "desserts",
        type: "veg",
    },
    {
        name: "Jalebi",
        description: "Crispy, golden spirals of dough soaked in syrup, served hot for a deliciously sweet, crunchy treat.",
        price: 100,
        image: { url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhoaB-x6XcKEWR69K5Ua6Zn5k3OHJOnC9phQ&s" },
        category: "desserts",
        type: "veg",
    },
    {
        name: "Kheer",
        description: "Creamy, rich rice pudding made with milk, sugar, and cardamom, topped with crunchy nuts for added texture.",
        price: 130,
        image: { url: "https://untoldrecipesbynosheen.com/wp-content/uploads/2024/05/kheer-featuredf.jpg" },
        category: "desserts",
        type: "veg",
    },
    {
        name: "Kesar Pista Kulfi",
        description: "Kulfi, a traditional Indian ice cream, flavored with saffron and pistachios for a nutty, creamy dessert experience.",
        price: 180,
        image: { url: "https://vaya.in/recipes/wp-content/uploads/2018/12/Kesar-Pista-Kulfi-Recipe.jpg" },
        category: "desserts",
        type: "veg",
    },
    {
        name: "Rasgulla Cheesecake",
        description: "A fusion of creamy cheesecake topped with spongy, syrup-soaked rasgullas for a rich, decadent dessert experience.",
        price: 220,
        image: { url: "https://www.chefajaychopra.com/assets/img/recipe/1-1669455485CherryRasgullaCheeseCakerecipewebp.webp" },
        category: "desserts",
        type: "veg",
    },
    {
        name: "Shahi Tukda",
        description: "Fried bread soaked in fragrant saffron milk, garnished with nuts and cardamom for a royal dessert indulgence.",
        price: 150,
        image: { url: "https://i.ytimg.com/vi/pxpJmXq2w7c/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDRpfQFOIGoj2l1K4wSF8FpeOmsFA" },
        category: "desserts",
        type: "veg",
    },
    {
        name: "Chocolate Samosa",
        description: "A twist on the classic samosa with a gooey chocolate filling, offering a perfect combination of crisp and melt-in-your-mouth goodness.",
        price: 100,
        image: { url: "https://static.toiimg.com/thumb/59297466.cms?width=1200&height=900" },
        category: "desserts",
        type: "veg",
    },
    {
        name: "D-Dine Special Mango Trifle",
        description: "A layered dessert featuring mango mousse, soft sponge cake, and fresh mango chunks for a tropical, refreshing treat.",
        price: 250,
        image: { url: "https://almmedia.almarai.com/Recipes/Mango-Trifle319202461843AM.jpg" },
        category: "desserts",
        type: "veg",
    },
    {
        name: "D-Dine Special Saffron Ras Malai",
        description: "Soft malai discs soaked in fragrant saffron-infused milk, garnished with pistachios for a rich, aromatic dessert experience.",
        price: 220,
        image: { url: "https://www.secondrecipe.com/wp-content/uploads/2021/12/kesar-rasmalai.jpg" },
        category: "desserts",
        type: "veg",
    },
];

module.exports = desserts;
